server:
  port: 8000

spring:
  application:
    name: xincan-transaction-config

eureka:
  instance:
    hostname: localhost
    port: 8761
    prefer-ip-address: true # 表示：将自己的ip注册到eureka
    instance-id: ${eureka.instance.hostname}:${server.port} # 以[IP地址:端口号]作为注册地址
#    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
#    lease-renewal-interval-in-seconds: 5
#    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
#    # 默认为90秒
#    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
#    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
#    # 该值至少应该大于 leaseRenewalIntervalInSeconds
#    lease-expiration-duration-in-seconds: 10
    metadata-map.zone: zone1

  client:
    registry-fetch-interval-seconds: 5 #新服务上线拉取eureka server服务注册信息频率，默认是30秒
    service-url:
      zone1: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    region: region-east
    availability-zones:
      region-east: zone1


logging:
  level:
    com.xincan.transaction: debug
  file: ./log/${spring.application.name}/${spring.application.name}.log